base_url = "https://curtainp.github.io"
title = ""
description = "enjoy coding and living"
default_language = "en"
output_dir = "public"
compile_sass = true
minify_html = true
build_search_index = false            # Keep this false, search is temporarily unsupported
generate_feeds = true
feed_filenames = ["atom.xml"]         # The file name of feed, "feed.xml" / "atom.xml" / "rss.xml", read docs for more info
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
highlight_theme = "nord"
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_themes_css = [
    { theme = "serene-light", filename = "hl-light.css"},
    { theme = "serene-dark", filename = "hl-dark.css"},
]
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]

name = "The Kaleidoscope"
id = "curtain"
bio = "enjoy coding and living"                          # Your bio
avatar = "img/avatar.webp"            # Your avatar
links = [                             # Your links
    { name = "GitHub", icon = "github", url = "https://github.com/curtainp" },
    { name = "Twitter", icon = "twitter", url = "https://x.com/curta1np" },
    { name = "Email", icon = "email", url = "mailto:w1410768946@gmail.com" },
]

homepage_layout = "about"             # "about" | "list" | "recent"
force_theme = false

sections = [
    { name = "blog", path = "/posts", is_external = false },
    # { name = "projects", path = "/projects", is_external = false },
    # { name = "about", path = "/about", is_external = false },
    # { name = "github", path = "https://github.com/<your-username>", is_external = true },
]
blog_section_path = "/posts"

nav_separator = "::"
nav_wrapper_left = "{"
nav_wrapper_right = "} ;"
nav_wrapper_separator = ","

blog_categorized = true               # Whether to categorize blog posts
blur_effect = true                    # Whether to turn on blur effect on navigation bar
back_to_top = true                    # Whether to show back-to-top button on post pages

toc = false                            # Whether to show Table-Of-Contents by default
copy = true                           # Whether to add a copy button on code blocks by default
comment = false                       # Whether to show giscus comment section by default, see https://giscus.app for more info
display_tags = true                   # Whether to display tags on post pages by default
truncate_summary = true              # Whether to truncate the summary of a post by default

outdate_alert = false                 # Whether to show outdate alert by default
outdate_alert_days = 120              # How many days will a post be outdated by default
outdate_alert_text_before = "This article was last updated "
outdate_alert_text_after = " days ago and may be out of date."

footer_copyright = "© 2024 curtain"
footer_credits = false                 # Whether to show "powered by zola and serene" in footer

not_found_title = "404"
not_found_error_text = "Not Found"
not_found_recover_text = "« back to home »"
